export enum AppRoutes {
	Dashboard = 'Dashboard',
	Login = 'Login',
	Welcome = 'Welcome',
	Wallets = 'Wallets',
	Wallet = 'Wallet',
	Incomes = 'Incomes',
	Expenses = 'Expenses',
	MonthlyBudget = 'MonthlyBudget',
	History = 'History',
	Transfers = 'Transfers',
	Settings = 'Settings',
	IncomeSources = 'IncomeSources',
	Currencies = 'Currencies',
	Categories = 'Categories',
	ExpenseSources = 'ExpenseSources',
	AccumulationFunds = 'AccumulationFunds',
	SavedFunds = 'SavedFunds',
	NotFound = 'NotFound',
	InternalServerError = 'InternalServerError'
}
